version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql.database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306" 
    volumes:
      - /var/lib/mysql:/var/lib/mysql:rw
    networks:
      - contact.infra
  app: 
    build: .
    container_name: contact.io
    command: sh -c 'npm run start:dev'
    environment:
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306,
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=CONTACTIO
      - JWT_PRIVATE_KEY=291919B05EE63995BABB3D9F0D038AD313F383A30F94B8D3D28B1A3F
      - JWT_EXPIRES=20h
    ports:
      - 5000:5000
    volumes:
      - $PWD/src:/app/src:ro
    depends_on:
      - mysql
    networks:
      - contact.infra

networks:
  contact.infra: 
    driver: bridge
