name: Contact.io Development

on: 
  push:
    branches: 
      - main
      - develop
  pull_request: 
    branches: 
      - main
      - develop

jobs: 

  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 19.x

      - name: Build
        run: |
          npm install
          npm run build

